<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogPart2 extends Seeder
{
    public function run(): void
    {
        DB::table('blogs')->insert([
            [ 'title' => 'Bahan Bangunan Murah Cikarang: Wajib Tahu 5 Material Dasar Ini', 'slug' => 'bahan-bangunan-murah-cikarang-wajib-tahu-5-material-dasar-ini', 'content' => '<!-- wp:image {"id":1328,"sizeSlug":"large","linkDestination":"none","style":{"color":{"duotone":"unset"}}} -->\n<figure class="wp-block-image size-large"><img src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/img_4532.jpg?w=1024" alt="" class="wp-image-1328" /></figure>\n<!-- /wp:image -->', 'image_path' => null, 'published_at' => '2025-07-12 00:02:03', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Perbedaan Pondasi Cakar Ayam dan Pondasi Batu Kali: Mana yang Lebih Cocok untuk Rumah Anda?', 'slug' => 'perbedaan-pondasi-cakar-ayam-dan-pondasi-batu-kali-mana-yang-lebih-cocok-untuk-rumah-anda', 'content' => '<!-- wp:image {"id":1334,"sizeSlug":"large","linkDestination":"none","className":"is-style-default","style":{"color":{"duotone":"unset"}}} -->\n<figure class="wp-block-image size-large is-style-default"><img src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/65b1dd9e77537_ori-edited.png" alt="" class="wp-image-1334" /></figure>\n<!-- /wp:image -->', 'image_path' => null, 'published_at' => '2025-07-17 20:54:03', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Kapan Waktu Terbaik untuk Membangun Rumah? Ini Jawaban Para Tukang', 'slug' => 'kapan-waktu-terbaik-untuk-membangun-rumah-ini-jawaban-para-tukang', 'content' => '<!-- wp:image {"id":1341,"sizeSlug":"full","linkDestination":"none","className":"is-style-default","style":{"color":{"duotone":"unset"}}} -->\n<figure class="wp-block-image size-full is-style-default"><img src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/a-group-of-construction-workers-building-a-two-story-house-in-edited.png" alt="" class="wp-image-1341" /></figure>\n<!-- /wp:image -->', 'image_path' => null, 'published_at' => '2025-07-17 21:02:12', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Hebel vs Bata Merah: Mana Lebih Kokoh & Hemat untuk Bangunan Anda?', 'slug' => 'apakah-hebel-bata-ringan-lebih-baik-dari-bata-merah', 'content' => '<!-- wp:image {"id":1463,"sizeSlug":"full","linkDestination":"none","style":{"color":{"duotone":"unset"}}} -->\n<figure class="wp-block-image size-full"><img src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/hebel-vs-bata-merah-mana-lebih-kokoh-hemat-untuk-bangunan-anda.webp" alt="" class="wp-image-1463" /></figure>\n<!-- /wp:image -->\n\n<!-- wp:heading -->\n<h2 class="wp-block-heading">Apakah Hebel (Bata Ringan) Lebih Baik dari Bata Merah?</h2>\n<!-- /wp:heading -->\n\n<!-- wp:paragraph -->\n<p>Memilih antara bata hebel vs bata merah sering bikin bingung, khususnya bagi yang sedang mencari bahan atau alat bangunan. Dalam tulisan ini, saya akan jelaskan secara gamblang – seperti ngobrol santai dengan content writer profesional, mengenai kelebihan, kekurangan, dan kapan sebaiknya memilih salah satunya, khususnya jika kamu berbelanja di <strong>Yen&nbsp;Bangunan Cikarang</strong>.</p>\n<!-- /wp:paragraph -->', 'image_path' => null, 'published_at' => '2025-07-17 21:14:04', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Toko Bangunan Grosir Cikarang, Pilihan Tepat untuk Proyek Developer!', 'slug' => 'toko-bangunan-grosir-cikarang-pilihan-tepat-untuk-proyek-developer', 'content' => '<img class="alignnone wp-image-1367 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/toko-bangunan-grosir-cikarang-pilihan-tepat-untuk-proyek-developer.webp" alt="TOKO BANGUNAN CIKARANG" width="950" height="550" />\n\n<span class="relative -mx-px my-[-0.2rem] rounded px-px py-[0.2rem] transition-colors duration-100 ease-in-out"><span dir="auto" style="vertical-align: inherit"><span dir="auto" style="vertical-align: inherit">Jika Anda adalah pengembang atau kontraktor yang sedang mencari </span></span></span><strong><span dir="auto" style="vertical-align: inherit">toko bangunan grosir Cikarang</span></strong>\n', 'image_path' => null, 'published_at' => '2025-07-29 13:33:06', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Tempat Jual Semen Murah di Cikarang, Panduan Lengkap untuk Proyek Anda!', 'slug' => 'tempat-jual-semen-murah-di-cikarang-panduan-lengkap-untuk-proyek-anda', 'content' => '<img class="alignnone wp-image-1386 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/tempat-jual-semen-murah-di-cikarang-panduan-lengkap-untuk-proyek-anda.webp" alt="Tempat Jual Semen Murah di Cikarang" width="950" height="550" />\n\n<span dir="auto" style="vertical-align: inherit">Saat memulai proyek bangunan, besar atau kecil, salah satu material paling krusial adalah </span><strong>semen</strong> .', 'image_path' => null, 'published_at' => '2025-07-29 14:38:50', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Rekomendasi Toko Material Bangunan Cikarang dengan Layanan Antar Cepat', 'slug' => 'rekomendasi-toko-material-bangunan-cikarang-dengan-layanan-antar-cepat', 'content' => '<img class="alignnone wp-image-1398 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/rekomendasi-toko-material-bangunan-cikarang-dengan-layanan-antar-cepat.webp" alt="Rekomendasi Toko Material Bangunan Cikarang dengan Layanan Antar Cepat" width="950" height="550" />', 'image_path' => null, 'published_at' => '2025-07-31 17:00:12', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Supplier Pasir & Batu Split Terdekat di Cikarang untuk Proyek Perumahan', 'slug' => 'supplier-pasir-batu-split-terdekat-di-cikarang-untuk-proyek-perumahan', 'content' => '<h2><img class="alignnone wp-image-1413 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/07/supplier-pasir-batu-split-terdekat-di-cikarang-untuk-proyek-perumahan-1.webp" alt="Supplier Pasir &amp; Batu Split Terdekat di Cikarang " width="950" height="550" /></h2>\n<h2>Mengenal Yen Bangunan Cikarang: Supplier Pasir Batu Cikarang Terpercaya</h2>', 'image_path' => null, 'published_at' => '2025-07-31 17:19:04', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Cara Memilih Toko Bangunan yang Tepat di Cikarang untuk Proyek Rumah Anda', 'slug' => 'cara-memilih-toko-bangunan-yang-tepat-di-cikarang-untuk-proyek-rumah-anda', 'content' => '<p><img class="alignnone wp-image-1424 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/08/cara-memilih-toko-bangunan-yang-tepat-di-cikarang-untuk-proyek-rumah-anda.webp" alt="Cara Memilih Toko Bangunan yang Tepat di Cikarang untuk Proyek Rumah Anda" width="950" height="550" /></p>\n<p>Membangun atau merenovasi rumah bukan perkara kecil. Mulai dari desain, anggaran, hingga pemilihan toko bangunan, semua memengaruhi hasil akhir proyek Anda. Di Cikarang, kawasan yang terus berkembang, menemukan <strong>toko bangunan terbaik di Cikarang</strong> bisa menjadi faktor kunci keberhasilan pembangunan Anda.</p>', 'image_path' => null, 'published_at' => '2025-08-01 15:28:56', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Apa Itu Hebel? Kenali Material Bangunan Modern yang Makin Populer', 'slug' => 'apa-itu-hebel-kenali-material-bangunan-modern-yang-makin-populer', 'content' => '<img class="alignnone wp-image-1438 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/08/apa-itu-hebel-kenali-material-bangunan-modern-yang-makin-populer.webp" alt="Apa Itu Hebel" width="950" height="550" />', 'image_path' => null, 'published_at' => '2025-08-05 13:22:23', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Perbandingan Harga Cat Tembok di Cikarang: Dulux, Avitex, dan Nippon Paint', 'slug' => 'perbandingan-harga-cat-tembok-di-cikarang-dulux-avitex-dan-nippon-paint', 'content' => '<p><img class="alignnone wp-image-1450 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/08/perbandingan-harga-cat-tembok-di-cikarang-dulux-avitex-dan-nippon-paint.webp" alt="Perbandingan Harga Cat Tembok di Cikarang Dulux, Avitex, dan Nippon Paint" width="950" height="550" /></p>', 'image_path' => null, 'published_at' => '2025-08-05 15:28:32', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Rekomendasi Toko Bangunan Cikarang dengan Layanan 24 Jam dan Tepat Waktu', 'slug' => 'rekomendasi-toko-bangunan-cikarang-dengan-layanan-24-jam-dan-tepat-waktu', 'content' => '<img class="alignnone wp-image-1459 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/08/rekomendasi-toko-bangunan-cikarang-dengan-layanan-24-jam-dan-tepat-waktu.webp" alt="Toko Bangunan Cikarang dengan Layanan 24 Jam" width="950" height="550" />', 'image_path' => null, 'published_at' => '2025-08-05 17:00:39', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
            [ 'title' => 'Beli Bahan Bangunan di Cikarang? Ini dia Toko Terpercaya Pilihan Warga Lokal!', 'slug' => 'beli-bahan-bangunan-di-cikarang-ini-dia-toko-terpercaya-pilihan-warga-lokal', 'content' => '<p><img class="alignnone wp-image-1482 size-full" src="https://andrian064.wordpress.com/wp-content/uploads/2025/08/beli-bahan-bangunan-di-cikarang-ini-dia-toko-terpercaya-pilihan-warga-lokal.webp" alt="Beli Bahan Bangunan di Cikarang? Ini dia Toko Terpercaya Pilihan Warga Lokal!" width="950" height="550" /></p>', 'image_path' => null, 'published_at' => '2025-08-06 22:13:03', 'author_id' => null, 'created_at' => now(), 'updated_at' => now() ],
        ]);
    }
}
